language: php

php:
  - 8.2

matrix:
  allow_failures:
    - php: 8.2

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --prefer-stable --no-interaction --prefer-source

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
